# Uncomment the next line to define a global platform for your project
# platform :ios, '17.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'iosApp' do
    use_frameworks!
    platform :ios, '18.0'
    pod 'composeApp', :path => '../composeApp'
    pod 'GoogleMaps', '9.1.1'
end
